recipe: default.v1

language: fr

pipeline:
  - name: WhitespaceTokenizer        # Tokeniseur simple pour le découpage des mots.
  - name: RegexFeaturizer            # Utilisation de motifs réguliers pour extraire des caractéristiques.
  - name: LexicalSyntacticFeaturizer # Extraction de caractéristiques lexicales et syntaxiques simples.
  - name: CountVectorsFeaturizer     # Vectorisation des mots pour une représentation simple.
    analyzer: word                   # Analyse des mots pour une vectorisation basique.
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier             # Classifieur pour les intentions et les entités.
    epochs: 100                      # Réduction du nombre d'époques pour un entraînement plus rapide.
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
    constrain_similarities: true

policies:
  - name: MemoizationPolicy
  # - name: RulePolicy
  #   core_fallback_threshold: 0.4     # Seuil pour le fallback côté dialogue.
  #   nlu_threshold: 0.4               # Seuil pour le fallback côté NLU.
  #   fallback_action_name: "action_default_fallback" # Action par défaut en cas de fallback.
  - name: UnexpecTEDIntentPolicy     # Politique pour gérer les intentions inattendues.
    max_history: 5
    epochs: 100
  - name: TEDPolicy                  # Politique basée sur les transformations.
    max_history: 5
    epochs: 100
    constrain_similarities: true

assistant_id: 20240625-110503-late-tap
